function [epochs, labels] = importcsv_v3(filename)
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: Y:\RBD-Wearables\raw\RBD_study2018\PSG\JR\EDF Files\WSJR006 epoch.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2020/02/06 17:22:16

%% Import the data
[~, ~, raw] = xlsread(filename,'Sheet1','A2:F389');
stringVectors = string(raw(:,[2,4,6]));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[1,3,5]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
Hyp = table;


%% Allocate imported array to column variable names
Hyp.Epoch = data(:,1);
Hyp.Stage = (stringVectors(:,1));
Hyp.Epoch1 = data(:,2);
Hyp.Stage1 = (stringVectors(:,2));
Hyp.Epoch2 = data(:,3);
Hyp.Stage2 = (stringVectors(:,3));
%%
epochs = reshape(table2cell(Hyp(:,[1,3,5])),[],1);
Stage = reshape(table2cell(Hyp(:,[2,4,6])),[],1);
keep = cellfun(@(x) ~strcmp(x,'-'), epochs)|cellfun(@(x) ~strcmp(x,'-'), Stage);
epochs = cell2mat(epochs(keep));
Stage = Stage(keep);
Stage(cellfun(@(x) strcmp(x,'NREM 4'),cellstr(Stage))) = {'NREM 3'};

CLASSES = {'\<Wake\>', '\<NREM 1\>', '\<NREM 2\>', '\<NREM 3\>', '\<REM\>'};
labels = cellfun(@(x) regexp(x,CLASSES), Stage,'uniformoutput',0);
labels = cell2mat(cellfun(@(x) ~cellfun(@isempty, x), labels,'UniformOutput',0));

rem = ~any(labels,2); %find rows of zero
epochs(rem) = [];
labels(rem,:) = [];

%% Clear temporary variables
clearvars data raw stringVectors;

end